admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
gestoria:
    resource: "@GestoriaBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
