# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        in_memory:
            memory: ~
        users:
            entity: { class: Gestoria\AdminBundle\Entity\User, property: email }    
    firewalls: 
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/admin/login$
            security: false    
        admin: 
            pattern: ^/admin
            provider:       users
            form_login:
                check_path:  /admin/login_check
                login_path:  /admin/login
                default_target_path: /admin/dashboard
                always_use_default_target_path: true
            logout:
                path:    /admin/logout
                target: /
            anonymous: ~    
        main:
            anonymous: ~
    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN,ROLE_SUPER_ADMIN] }  
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
    encoders:
        Gestoria\AdminBundle\Entity\User: {algorithm: sha512, encode_as_base64: true, iterations: 10}
    role_hierarchy: 
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN,ROLE_ADMIN]